import Document, { Html, Head, Main, NextScript } from "next/document";
import loader from "../loader";

//I added this document because is the only way which i have to add new fonts from google fonts, and use them with talwind.
function MyDocument() {
  return (
    <Html lang="en">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <head>
          <style>{loader}</style>
        </head>

        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;400;600&family=Roboto:wght@100;400&display=swap"
          rel="stylesheet"
        ></link>

        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;400&display=swap"
          rel="stylesheet"
        />
      </Head>

      <body>
        <div id="globalLoader">
          <span className="loader"></span>
        </div>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}

export default MyDocument;
